version: "3.9"

services:
  web:
    build: ./app
    ports:
            - "11699:11699"
    restart: on-failure
    volumes:
      - ./app:/app
    command: python3 Main.py
    deploy:
      resources:
        limits:
          memory: 1GB
